### ISSUE TITLE
PDF upload on ONETEAM workteam not working

### ISSUE THREAD

**Issue by decasadecasa** [level73/membernet#203]
wont save pdf

**Comment by IronRunes** [comment]
@decasadecasa is this the dev or prod environment? 
how big is said pdf (in terms of file size)?

**Comment by IronRunes** [comment]
ah just saw the project, ok, on to it!

**Comment by IronRunes** [comment]
This should work now, let me know!

**Comment by decasadecasa** [comment]
Still not working ( I am testing files under ONETEAM work teams)

**Comment by decasadecasa** [comment]
same goes for PDF saving in other entities (NES/CBI reports tested and didnt work)

**Comment by IronRunes** [comment]
fixed now, please test
