### ISSUE TITLE
When assigning the Council Representative role in FindMe, Membernet creates a duplicate of the contact and actually doesn't assign the Council Representative role to it.

### ISSUE THREAD

**Issue by exhej11** [level73/membernet#45]
![jm](https://user-images.githubusercontent.com/48788375/56717050-1d5f6300-673c-11e9-9563-b65410291d1c.PNG)
![kw](https://user-images.githubusercontent.com/48788375/56717056-1fc1bd00-673c-11e9-9f1f-da7f092cd396.PNG)
In the case of Kathrin Wessendorf I added the Council Representative in MNET manually because it appeared not to sync with FindMe

**Comment by exhej11** [comment]
Same issue with Regional Steering Committee members; they have all become duplicates in MNET, sometimes even triplicate as the case of Kathrin Wessendorf.

**Comment by exhej11** [comment]
![Capture](https://user-images.githubusercontent.com/48788375/56729062-94a0f100-6754-11e9-9572-da1f21801f14.PNG)
In this case (have not checked them all) the contact is save 5 separate times. It might be possible that it is the same case for other contacts too.

**Comment by IronRunes** [comment]
the bug that was causing this is resolved.

**Comment by exhej11** [comment]
But the entries that are already created we need to delete them manually right? As I still see them appear in MNET.

**Comment by exhej11** [comment]
Still not working!
![fi](https://user-images.githubusercontent.com/48788375/56791031-5fed7200-6806-11e9-9283-ac78a8597bac.PNG)
While in FindMe the Council Representative filter works and I just assigned the role to Raed Gharib MNET doesn't update accordingly.
![seeds](https://user-images.githubusercontent.com/48788375/56791159-acd14880-6806-11e9-875c-c2df86bc4be2.PNG)
(I am not sure if the duplication is caused from this issue as well because I didn't check before I assigned the role)

**Comment by IronRunes** [comment]
it actually is. it just isn't displayed on the frontend. please check in the contacts management. If we do want to have that kind of data show on the membernet frontend, we should open a new issue. :)

**Comment by decasadecasa** [comment]
Its not a problem to have council/steering committee tags show up on mnet, no need to open anew issue for that. Just duplicates that were the issue. Thanks

**Comment by IronRunes** [comment]
displayed on the frontend. :)

**Comment by decasadecasa** [comment]
This issue is still reoccurring. Are we supposed to manage these tags from mnet or can they be pulled from findme? (not working currently). It would be good to understand what needs to be manually managed and what can be pulled.

**Comment by IronRunes** [comment]
it is now also showing up on the backend. there was a misalignment between the role ID's of the two platforms. We'll need to re-save the council reps and the regional steering committee profiles in findme

**Comment by decasadecasa** [comment]
re assign the roles or delete the contact and make it again?

**Comment by exhej11** [comment]
While reassigning the roles seems to work, looks like we have another issue we re facing. Since there were duplicates created from a previous bug when reassigning the role the action happens in the duplicate. When I got rid of the duplicate from FUNDE's Ismael Merlos the contact which was initally there did not sync with the action in FindMe, meaning that FindMe is synced with the duplicates in MNET and not with the primary, older contact saved before and that might have other roles assigned such as (Alternate/Focal Point)

**Comment by exhej11** [comment]
![1Capture](https://user-images.githubusercontent.com/48788375/56904232-29ca1f80-6a9e-11e9-9877-e341f7a5a2d2.PNG)
